fix: syntax error from shellcheck analysis

diff --git a/bin/uninstall-dotnet b/bin/uninstall-dotnet
--- a/bin/uninstall-dotnet
+++ b/bin/uninstall-dotnet
@@ -4,11 +4,9 @@
 # Licensed under the MIT license. See LICENSE file in the project root for full license information.
 #
 
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-
 current_userid=$(id -u)
 
-if [ $current_userid -ne 0 ]; then
+if [ "$current_userid" -ne 0 ]; then
     echo "$(basename "$0") uninstallation script requires superuser privileges to run" >&2
     exit 1
 fi
@@ -18,7 +16,9 @@ dotnet_install_root="/usr/local/share/dotnet"
 dotnet_path_file="/etc/paths.d/dotnet"
 
 remove_dotnet_pkgs(){
-    installed_pkgs=($(pkgutil --pkgs | grep $dotnet_pkg_name_suffix))
+    # installed_pkgs=($(pkgutil --pkgs | grep $dotnet_pkg_name_suffix))
+    local installed_pkgs
+    mapfile -t installed_pkgs < <(pkgutil --pkgs | grep $dotnet_pkg_name_suffix)
 
     for i in "${installed_pkgs[@]}"
     do
@@ -28,7 +28,9 @@ remove_dotnet_pkgs(){
 }
 
 remove_dotnet_pkgs
-[ "$?" -ne 0 ] && echo "Failed to remove dotnet packages." >&2 && exit 1
+if ! remove_dotnet_pkgs; then
+     echo "Failed to remove dotnet packages." >&2 && exit 1
+fi
 
 echo "Deleting install root - $dotnet_install_root" >&2
 rm -rf "$dotnet_install_root"
